# Generated by Django 3.2.10 on 2024-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=800, verbose_name='Ширина списка (px)')),
                ('height', models.PositiveIntegerField(default=600, verbose_name='Высота списка (px)')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет фона (HEX)')),
            ],
        ),
    ]
