# Generated by Django 3.2.10 on 2024-11-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newssettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsSettings',
        ),
    ]
